### ISSUE TITLE
ERR Cannot access 've' before initialization: ReferenceError: Cannot access 've' before initialization

### ISSUE THREAD

**Issue by PieterVanZyl-Dev** [ankitbko/vscode-pull-request-azdo#55]
`  ERR Cannot access 've' before initialization: ReferenceError: Cannot access 've' before initialization
    at c:\Users\pivanzyl\.vscode\extensions\ankitbko.vscode-pull-request-azdo-0.0.23\dist\extension.js:198:35334
    at l.fire (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
    at c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:7292
    at l.fire (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
    at S.$onDidChangePassword (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:99810)
    at d._doInvokeHandler (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12815)
    at d._invokeHandler (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12507)
    at d._receiveRequest (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:11160)
    at d._receiveOneMessage (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:9960)
    at c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:8064
    at l.fire (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
    at E.fire (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15634)
    at c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:29816
    at l.fire (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
    at E.fire (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15634)
    at t._receiveMessage (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20892)
    at c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17778
    at l.fire (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
    at c.acceptChunk (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12995)
    at c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12343
    at Socket.b (c:\Users\pivanzyl\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:13287)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)`

- Extension version:v0.0.23
- VSCode Version:1.57.1
- OS:Windows 10 x86

Steps to Reproduce:

1. Start VS code
2. Was requested a PAT, put it in and got this error.

**Comment by PieterVanZyl-Dev** [comment]
Extra Information:

ORG URL IS SET TO: 
Which is a private hosted azure devops server.

https://devops.za.company.com/unit/

and the project would normally follow /ABC

Is it possible that fact that it is a private server is a problem ? 
Can't think that that is related to the

**Comment by ankitbko** [comment]
Hey I released a new version of extension 0.0.24. It has few bug fixes but nothing related to this. However, can you still try to replicate this issue after updating the extension? Also can you please set `azdoPullRequests.logLevel` to `debug` before replicating.

I dont know why it is happening, it may be related to extension unable to reach your private server due to some proxy requirement. Need to check a bit.

Also `[Info] C:\Users\pivanzyl.ssh\config: ENOENT: no such file or directory, open 'C:\Users\pivanzyl.ssh\config'` seems to miss an addition `\` before `.ssh`.

**Comment by PieterVanZyl-Dev** [comment]
Switching to logLevel Debug.

Could it be possible that we need to add something here

`import * as vscode from 'vscode';

export class AzdoManager {
	// TODO WTF Does this do?
	private _servers: Map<string, boolean> = new Map()
		.set('dev.azure.com', true)
		.set('ssh.dev.azure.com', true)
		.set('vs-ssh.visualstudio.com', true);

	public async isAzdo(host: vscode.Uri): Promise<boolean> {
		if (host === null) {
			return false;
		}

		for (const [key, value] of this._servers) {
			if (key.includes(host.authority)) {
				return value;
			}
		}

		return host.authority.includes('.visualstudio.com');
	}
}`

**Comment by PieterVanZyl-Dev** [comment]
Looks to me like my server wouldn't work with this isAzdo check.

**Comment by ankitbko** [comment]
oh yes.. good catch. I will make it configurable.

**Comment by PieterVanZyl-Dev** [comment]
Debug log

I also tried to add an extra remote branch, super interesting logs.

ssh still got the same error should I put a file there ?

[Debug 1624539114.481s] C:\Users\pivanzyl\.ssh\config: ENOENT: no such file or directory, open 'C:\Users\pivanzyl\.ssh\config'
[Debug 1624539116.696s] AzdoRepository> projectName is DLD
[Debug 1624539116.696s] AzdoRepository> orgUrl is https://devops.za.company.com/unit/
[Debug 1624539141.024s] AzdoRepository> Auth> Successful: Logged userid: 2164d41e-f340-4540-88f6-ad7f0c1fe77d
[Debug 1624539141.03s] Looking for git repository
[Debug 1624539141.033s] Git repository found, initializing review manager and pr tree view.
[Debug 1624539141.597s] Review> Validate state in progress
[Debug 1624539141.598s] Review> Validating state...
[Debug 1624539142.663s] Review> Queuing additional validate state
[Debug 1624539143.423s] Review> no matching pull request metadata found for current branch feature/kpi-rounded-card
[Debug 1624539143.424s] Review> no matching pull request metadata found on GitHub for current branch feature/kpi-rounded-card
[Debug 1624539143.426s] Review> Validating state...
[Debug 1624539143.429s] FolderRepositoryManager> No remote with name 'origin' found. All other remotes: 
[Debug 1624539143.429s] FolderRepositoryManager> No remote with name 'upstream' found. All other remotes: 
[Debug 1624539143.429s] FolderRepositoryManager> Displaying configured remotes: origin, upstream
[Debug 1624539143.562s] FolderRepositoryManager> No Azdo remotes found. All remotes: 
[Debug 1624539144.956s] Review> no matching pull request metadata found for current branch feature/kpi-rounded-card
[Debug 1624539144.956s] Review> no matching pull request metadata found on GitHub for current branch feature/kpi-rounded-card
[Debug 1624539232.887s] FolderRepositoryManager> No remote with name 'origin' found. All other remotes: 
[Debug 1624539232.887s] FolderRepositoryManager> No remote with name 'upstream' found. All other remotes: 
[Debug 1624539232.887s] FolderRepositoryManager> No remote with name 'develop' found. All other remotes: 
[Debug 1624539232.887s] FolderRepositoryManager> Displaying configured remotes: origin, upstream, develop
[Debug 1624539232.906s] FolderRepositoryManager> No Azdo remotes found. All remotes: 

Not finding any remotes here, but auth seems to be successful ?

**Comment by PieterVanZyl-Dev** [comment]
There are remotes in 'origin'
![image](https://user-images.githubusercontent.com/20579513/123266955-c791cb80-d4fc-11eb-8ab4-a164f0b6e7e7.png)

**Comment by PieterVanZyl-Dev** [comment]
I'll test once #56 is completed

and let you know if that fixes anything.

**Comment by ankitbko** [comment]
I have published version 0.0.25 which should be available in next 5-10 min. Please try and let me know if it fixes this.

**Comment by PieterVanZyl-Dev** [comment]
Extension now works correctly !

You can probably add to the readme that this extension supports Private Azure Devop Servers too ;)

I'll test it now, first time it works with the private server.
